In [2]:
import pandas as pd

In [3]:
station_data = pd.read_csv("C:/Users/ASIA_07/Desktop/Compas 과제/고양시 자전거/고양시자전거data/29.지하철 역별 이용객수.csv")

station_location = pd.read_csv("C:/Users/ASIA_07/Desktop/Compas 과제/고양시 자전거/고양시자전거data/19.전철역_공간정보.csv")

In [4]:
station_data.columns

Index(['호선명', '역명', '행정구역', '년월구분', '승하차구분', '월요일_합계', '화요일_합계', '수요일_합계',
       '목요일_합계', '금요일_합계', '토요일_합계', '일요일_합계', '모든요일_합계', '월요일_평균', '화요일_평균',
       '수요일_평균', '목요일_평균', '금요일_평균', '토요일_평균', '일요일_평균', '모든요일_평균'],
      dtype='object')

In [5]:
station_data = station_data[station_data['승하차구분'] == '총승하차']    # 총승하차만 남김.

In [6]:
station_data = station_data.reset_index(drop=True)

In [7]:
station_list = ['호선명','역명','승하차구분','모든요일_합계']

In [8]:
station_data = station_data[station_list]
station_data

    호선명   역명 승하차구분   모든요일_합계
0   3호선   지축  총승하차   1012460
1   경의선   화전  총승하차   1799161
2   경의선   강매  총승하차   1859720
3   경의선   행신  총승하차   5568132
4   경의선   능곡  총승하차   2637855
5   경의선   곡산  총승하차    404413
6   경의선   백마  총승하차   4733842
7   경의선   풍산  총승하차   3577046
8   경의선   일산  총승하차   6808074
9   경의선   탄현  총승하차   5356327
10  경원선   원흥  총승하차   5757420
11  일산선   지축  총승하차    170378
12  일산선   삼송  총승하차  11526325
13  일산선   원당  총승하차   8607849
14  일산선   화정  총승하차  14522105
15  일산선   대곡  총승하차   1094752
16  일산선   백석  총승하차   8533226
17  일산선   마두  총승하차   6222179
18  일산선  정발산  총승하차   6843625
19  일산선   주엽  총승하차   7234466
20  일산선   대화  총승하차  10008025

In [9]:
station_location

,rail_nm,station_nm,lot_num_addr,road_nm_addr,X,Y
0,3호선,대곡,경기도 고양시 덕양구 대장동 420-1,경기도 고양시 덕양구 대주로107번길 71-81,126.809614,37.632306
1,3호선,대화,경기도 고양시 일산서구 대화동 2221,경기도 고양시 일산서구 중앙로 지하 1569,126.747206,37.675846
2,경의중앙,일산,경기도 고양시 일산서구 일산동 655-691,경기도 고양시 일산서구 경의로 672,126.770067,37.682007
3,3호선,백석,경기도 고양시 일산동구 백석동 1538,경기도 고양시 일산동구 중앙로 지하 1042,126.788148,37.642953
4,경의중앙,대곡,경기도 고양시 덕양구 대장동 420-1,경기도 고양시 덕양구 대주로 107번길 71-81,126.811047,37.631615
5,경의중앙,강매,경기도 고양시 덕양구 행신동 1115-1,경기도 고양시 덕양구 소원로 202,126.844436,37.612290
6,경의중앙,백마,경기도 고양시 일산동구 백석동 92,경기도 고양시 일산동구 경의로 318,126.794067,37.658431
7,경의중앙,능곡,경기도 고양시 덕양구 토당동 454-3,경기도 고양시 덕양구 토당로 35,126.820838,37.618765
8,경의중앙,풍산,경기도 고양시 일산동구 풍동 1042,경기도 고양시 일산동구 경의로 486,126.786528,37.671815
9,경의중앙,행신,경기도 고양시 덕양구 행신동 812,경기도 고양시 덕양구 소원로 114,126.834117,37.612170
10,경의중앙,화전(한국항공대),경기도 고양시 덕양구 화전동 183-10,경기도 고양시 덕양구 화랑로 53,126.867947,37.603298
11,경의중앙,탄현,경기도 고양시 일산서구 덕이동 238번지,경기도 고양시 일산서구 경의로 856,126.761166,37.693857
12,3호선,주엽,경기도 고양시 일산서구 주엽동 166-7,경기도 고양시 일산서구 중앙로 지하 1432,126.761230,37.670142
13,3호선,정발산,경기도 고양시 일산동구 마두동 1123,경기도 고양시 일산동구 중앙로 지하 1270,126.773359,37.659493
14,3호선,마두,경기도 고양시 일산동구 마두동 765-1,경기도 고양시 일산동구 중앙로 지하 1180,126.777650,37.652174
15,3호선,화정,경기도 고양시 덕양구 화정동 1098,경기도 고양시 덕양구 화정로 지하60,126.832666,37.634597
16,경의중앙,곡산,경기도 고양시 일산동구 백석동 1185-1,경기도 고양시 일산동구 경의로 160,126.801514,37.646127
17,3호선,원흥,경기도 고양시 덕양구 원흥동 569-15,경기도 고양시 덕양구 권율대로 681,126.872600,37.650746
18,3호선,원당,경기도 고양시 덕양구 성사동 410-7,경기도 고양시 덕양구 고양대로 1429,126.843030,37.653316
19,3호선,삼송,경기도 고양시 덕양구 삼송동 18-5,경기도 고양시 덕양구 삼송로 지하 194,126.895590,37.653110
20,3호선,지축역,NaN,경기도 고양시 덕양구 삼송로 300,126.913728,37.648118

In [10]:
# 지축 중복값 제거.

for i in range(len(station_data)) :
    for j in range(len(station_data)) :
        
        if i!=j and station_data['역명'].iloc[i] == station_data['역명'].iloc[j] :
            print(i, j)
            
station_data['모든요일_합계'].iloc[0] = station_data['모든요일_합계'].iloc[0] + station_data['모든요일_합계'].iloc[11]
            

station_data = station_data.drop(11)     # 여러번돌리지 않아야 함! 
station_data = station_data.reset_index(drop=True)
station_data

0 11
11 0

    호선명   역명 승하차구분   모든요일_합계
0   3호선   지축  총승하차   1182838
1   경의선   화전  총승하차   1799161
2   경의선   강매  총승하차   1859720
3   경의선   행신  총승하차   5568132
4   경의선   능곡  총승하차   2637855
5   경의선   곡산  총승하차    404413
6   경의선   백마  총승하차   4733842
7   경의선   풍산  총승하차   3577046
8   경의선   일산  총승하차   6808074
9   경의선   탄현  총승하차   5356327
10  경원선   원흥  총승하차   5757420
11  일산선   삼송  총승하차  11526325
12  일산선   원당  총승하차   8607849
13  일산선   화정  총승하차  14522105
14  일산선   대곡  총승하차   1094752
15  일산선   백석  총승하차   8533226
16  일산선   마두  총승하차   6222179
17  일산선  정발산  총승하차   6843625
18  일산선   주엽  총승하차   7234466
19  일산선   대화  총승하차  10008025

In [11]:
station_data['X'] = 0
station_data['Y'] = 0

In [12]:
station_data

    호선명   역명 승하차구분   모든요일_합계  X  Y
0   3호선   지축  총승하차   1182838  0  0
1   경의선   화전  총승하차   1799161  0  0
2   경의선   강매  총승하차   1859720  0  0
3   경의선   행신  총승하차   5568132  0  0
4   경의선   능곡  총승하차   2637855  0  0
5   경의선   곡산  총승하차    404413  0  0
6   경의선   백마  총승하차   4733842  0  0
7   경의선   풍산  총승하차   3577046  0  0
8   경의선   일산  총승하차   6808074  0  0
9   경의선   탄현  총승하차   5356327  0  0
10  경원선   원흥  총승하차   5757420  0  0
11  일산선   삼송  총승하차  11526325  0  0
12  일산선   원당  총승하차   8607849  0  0
13  일산선   화정  총승하차  14522105  0  0
14  일산선   대곡  총승하차   1094752  0  0
15  일산선   백석  총승하차   8533226  0  0
16  일산선   마두  총승하차   6222179  0  0
17  일산선  정발산  총승하차   6843625  0  0
18  일산선   주엽  총승하차   7234466  0  0
19  일산선   대화  총승하차  10008025  0  0

In [13]:
for i in range(len(station_data['역명'])):
    for j in range(len(station_location['station_nm'])):
        if station_data['역명'].iloc[i] == station_location['station_nm'].iloc[j] :
            print(i, station_data['역명'].iloc[i], station_location['X'].iloc[j], station_location['Y'].iloc[j])
            station_data['X'].iloc[i] = station_location['X'].iloc[j]
            station_data['Y'].iloc[i] = station_location['Y'].iloc[j]
            break

for i in range(len(station_data)) :
    if station_data['X'].iloc[i] == 0 :
        print('위치정보 못 받은 역은 ', station_data['역명'].iloc[i])


for i in range(len(station_location)) :
    if '지축' in station_location['station_nm'].iloc[i] or '화전' in station_location['station_nm'].iloc[i] :
        print('station_location 파일에서 ',i, station_location['station_nm'].iloc[i])
        
        
        
        

station_data['X'].iloc[0] = station_location['X'].iloc[20]
station_data['Y'].iloc[0] = station_location['Y'].iloc[20]
     
station_data['X'].iloc[1] = station_location['X'].iloc[10]
station_data['Y'].iloc[1] = station_location['Y'].iloc[10]

station_data  # 이제 위치는 다 뽑고, 정렬만 다시 하면 된다

2 강매 126.84443637 37.61228963
3 행신 126.834117 37.61217
4 능곡 126.82083836 37.61876543
5 곡산 126.80151439 37.64612663
6 백마 126.794067 37.658431
7 풍산 126.786528 37.671815
8 일산 126.77006749 37.68200683
9 탄현 126.76116553 37.69385707
10 원흥 126.87260033 37.65074577
11 삼송 126.89558955 37.65310988
12 원당 126.84303034 37.65331645
13 화정 126.83266635 37.63459661
14 대곡 126.809614 37.632306
15 백석 126.7881483 37.64295283
16 마두 126.77764972 37.65217351
17 정발산 126.77335864 37.65949317
18 주엽 126.76122972 37.67014215
19 대화 126.747206 37.675846
위치정보 못 받은 역은  지축
위치정보 못 받은 역은  화전
station_location 파일에서  10 화전(한국항공대)
station_location 파일에서  20 지축역

C:\anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

    호선명   역명 승하차구분   모든요일_합계           X          Y
0   3호선   지축  총승하차   1182838  126.913728  37.648118
1   경의선   화전  총승하차   1799161  126.867947  37.603298
2   경의선   강매  총승하차   1859720  126.844436  37.612290
3   경의선   행신  총승하차   5568132  126.834117  37.612170
4   경의선   능곡  총승하차   2637855  126.820838  37.618765
5   경의선   곡산  총승하차    404413  126.801514  37.646127
6   경의선   백마  총승하차   4733842  126.794067  37.658431
7   경의선   풍산  총승하차   3577046  126.786528  37.671815
8   경의선   일산  총승하차   6808074  126.770067  37.682007
9   경의선   탄현  총승하차   5356327  126.761166  37.693857
10  경원선   원흥  총승하차   5757420  126.872600  37.650746
11  일산선   삼송  총승하차  11526325  126.895590  37.653110
12  일산선   원당  총승하차   8607849  126.843030  37.653316
13  일산선   화정  총승하차  14522105  126.832666  37.634597
14  일산선   대곡  총승하차   1094752  126.809614  37.632306
15  일산선   백석  총승하차   8533226  126.788148  37.642953
16  일산선   마두  총승하차   6222179  126.777650  37.652174
17  일산선  정발산  총승하차   6843625  126.773359  37.659493
18  일산선   주엽  총승하차   7234466  126.761230  37.670142
19  일산선   대화  총승하차  10008025  126.747206  37.675846

In [14]:
station_data = station_data.sort_values(by='모든요일_합계',ascending=False)  # 사람들이 많이 다니는 순으로 정렬
station_data

station_data = station_data.reset_index(drop=True)   #다시 보기좋게 인덱스 정렬
station_data


station_data1 = station_data.copy()   # 저장해놓기
station_data = station_data1


station_data    # 완료

    호선명   역명 승하차구분   모든요일_합계           X          Y
0   일산선   화정  총승하차  14522105  126.832666  37.634597
1   일산선   삼송  총승하차  11526325  126.895590  37.653110
2   일산선   대화  총승하차  10008025  126.747206  37.675846
3   일산선   원당  총승하차   8607849  126.843030  37.653316
4   일산선   백석  총승하차   8533226  126.788148  37.642953
5   일산선   주엽  총승하차   7234466  126.761230  37.670142
6   일산선  정발산  총승하차   6843625  126.773359  37.659493
7   경의선   일산  총승하차   6808074  126.770067  37.682007
8   일산선   마두  총승하차   6222179  126.777650  37.652174
9   경원선   원흥  총승하차   5757420  126.872600  37.650746
10  경의선   행신  총승하차   5568132  126.834117  37.612170
11  경의선   탄현  총승하차   5356327  126.761166  37.693857
12  경의선   백마  총승하차   4733842  126.794067  37.658431
13  경의선   풍산  총승하차   3577046  126.786528  37.671815
14  경의선   능곡  총승하차   2637855  126.820838  37.618765
15  경의선   강매  총승하차   1859720  126.844436  37.612290
16  경의선   화전  총승하차   1799161  126.867947  37.603298
17  3호선   지축  총승하차   1182838  126.913728  37.648118
18  일산선   대곡  총승하차   1094752  126.809614  37.632306
19  경의선   곡산  총승하차    404413  126.801514  37.646127

In [24]:
station_data.to_csv('station_on_off_and_location.csv',mode='w')

    호선명   역명 승하차구분   모든요일_합계           X          Y
0   일산선   화정  총승하차  14522105  126.832666  37.634597
1   일산선   삼송  총승하차  11526325  126.895590  37.653110
2   일산선   대화  총승하차  10008025  126.747206  37.675846
3   일산선   원당  총승하차   8607849  126.843030  37.653316
4   일산선   백석  총승하차   8533226  126.788148  37.642953
5   일산선   주엽  총승하차   7234466  126.761230  37.670142
6   일산선  정발산  총승하차   6843625  126.773359  37.659493
7   경의선   일산  총승하차   6808074  126.770067  37.682007
8   일산선   마두  총승하차   6222179  126.777650  37.652174
9   경원선   원흥  총승하차   5757420  126.872600  37.650746
10  경의선   행신  총승하차   5568132  126.834117  37.612170
11  경의선   탄현  총승하차   5356327  126.761166  37.693857
12  경의선   백마  총승하차   4733842  126.794067  37.658431
13  경의선   풍산  총승하차   3577046  126.786528  37.671815
14  경의선   능곡  총승하차   2637855  126.820838  37.618765
15  경의선   강매  총승하차   1859720  126.844436  37.612290
16  경의선   화전  총승하차   1799161  126.867947  37.603298
17  3호선   지축  총승하차   1182838  126.913728  37.648118
18  일산선   대곡  총승하차   1094752  126.809614  37.632306
19  경의선   곡산  총승하차    404413  126.801514  37.646127

# <시각화> 여기부터는 -  운영이력에서 랜덤으로 n개 뽑은다음에, 거기에서 대여->반납 장소를 쌍으로 찍어보자

In [263]:
import pandas as pd

read = pd.read_csv('C:/Users/ASIA_07/Desktop/Compas 과제/고양시 자전거/고양시자전거data/01.운영이력.csv')

a = read.sample(150)      # dataframe에서 random하게 sample을 뽑아내는 방법.

C:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [264]:
station_info = pd.read_csv('C:/Users/ASIA_07/Desktop/Compas 과제/고양시 자전거/고양시자전거data/02.자전거스테이션.csv')

In [265]:
station_info

     Station_ID          STATION_NAME  거치대 수량         위도          경도
0           101          어울림마을 701동 앞      20  37.654775  126.834584
1           103          대림e-편한세상106동      20  37.660442  126.840377
2           104               탄현마을8단지      25  37.698523  126.766042
3           105             KT 덕양지사 앞      20  37.655244  126.839261
4           106           원당역 앞 공영주차장      30  37.653410  126.842530
..          ...                   ...     ...        ...         ...
159         350  ★하이파크5단지 502동앞 버스정류장      20  37.697867  126.753089
160         351          ◆일산에듀포레 푸르지오      40  37.702259  126.767231
161         352            ◆꿈에그린203동앞      40  37.666425  126.749244
162         353            ◆꿈에그린106동앞      40  37.666720  126.750784
163         992                ★피프틴센터       4  37.637529  126.833760

[164 rows x 5 columns]

In [266]:
need_info = ['LEAS_STATION', 'RTN_STATION']
b = a[need_info]

In [267]:
b = b.reset_index(drop=True)

In [268]:
# 대여한 자전거정류장 위도경도 채우기
b['대여_X'] = 0
b['대여_Y'] = 0


for i in range(len(b['LEAS_STATION'])):
    for j in range(len(station_info['Station_ID'])):
        if b['LEAS_STATION'].iloc[i] == station_info['Station_ID'].iloc[j] :
            print(i, b['LEAS_STATION'].iloc[i], station_info['Station_ID'].iloc[j])
            b['대여_X'].iloc[i] = station_info['위도'].iloc[j]
            b['대여_Y'].iloc[i] = station_info['경도'].iloc[j]
            break

0 310 310
1 321 321
2 217 217
3 114 114
4 309 309
5 247 247
6 309 309
7 309 309
8 137 137
9 330 330
10 326 326
11 260 260
12 215 215
13 315 315
14 254 254
15 232 232
16 207 207
17 305 305
18 221 221
19 320 320
20 254 254
21 230 230
22 330 330
23 226 226
24 105 105
25 127 127
26 234 234
27 128 128
28 222 222
29 211 211
30 229 229
31 340 340
32 319 319
33 231 231
34 215 215
35 210 210
36 308 308
37 246 246
38 214 214
39 211 211
40 212 212
41 256 256
42 245 245
43 321 321
44 203 203
45 229 229
46 112 112
47 312 312
48 302 302
49 256 256
50 309 309
51 253 253
52 316 316
53 231 231
54 140 140
55 255 255
56 211 211
57 210 210
58 212 212
59 311 311
60 312 312
61 342 342
62 235 235
63 214 214
64 315 315
65 343 343
66 217 217
67 234 234
68 215 215
69 339 339
70 253 253
71 112 112
72 227 227
73 119 119
74 232 232
75 308 308
76 234 234
77 226 226
78 307 307
79 309 309
80 331 331
81 254 254
82 164 164
83 333 333
84 203 203
85 163 163
86 334 334
87 113 113
88 227 227
89 233 233
90 211 211
91 309 309
92 318 318
93 317 317
94 204 204
95 206 206
96 138 138
97 245 245
98 326 326
99 214

C:\anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

214
100 321 321
101 114 114
102 222 222
103 235 235
104 238 238
105 211 211
106 164 164
107 317 317
108 227 227
109 306 306
110 211 211
111 227 227
112 342 342
113 232 232
114 318 318
115 254 254
116 330 330
117 305 305
118 130 130
119 210 210
120 310 310
121 254 254
122 212 212
123 257 257
124 246 246
125 203 203
126 306 306
127 259 259
128 259 259
129 219 219
130 254 254
131 237 237
132 334 334
133 259 259
134 213 213
135 317 317
136 148 148
137 253 253
138 235 235
139 101 101
140 211 211
141 221 221
142 207 207
143 314 314
144 166 166
145 339 339
146 328 328
147 315 315
148 309 309
149 219 219

In [269]:
# 반납한 자전거 정류장 위도경도 찍기
b['반납_X'] = 0
b['반납_Y'] = 0


for i in range(len(b['RTN_STATION'])):
    for j in range(len(station_info['Station_ID'])):
        if b['RTN_STATION'].iloc[i] == station_info['Station_ID'].iloc[j] :
            print(i, b['RTN_STATION'].iloc[i], station_info['Station_ID'].iloc[j])
            b['반납_X'].iloc[i] = station_info['위도'].iloc[j]
            b['반납_Y'].iloc[i] = station_info['경도'].iloc[j]
            break

0 342 342
1 211 211
2 215 215
4 342 342
5 210 210
6 307 307
7 309 309
8 119 119
10 327 327
11 227 227
12 204 204
13 315 315
14 254 254
15 225 225
18 221 221
19 309 309
20 254 254
21 225 225
22 305 305
23 226 226
24 253 253
25 127 127
26 222 222
27 138 138
28 220 220
29 231 231
30 238 238
32 321 321
33 235 235
34 222 222
35 343 343
36 254 254
37 229 229
39 203 203
40 252 252
41 221 221
43 320 320
44 260 260
45 227 227
46 126 126
47 210 210
48 319 319
49 203 203
50 311 311
51 211 211
52 314 314
53 259 259
54 121 121
55 220 220
56 252 252
57 302 302
58 260 260
60 309 309
61 343 343
62 233 233
63 214 214
64 315 315
65 311 311
66 214 214
67 215 215
68 217 217
69 305 305
70 253 253
71 101 101
72 316 316
73 103 103
74 310 310
75 214 214
76 229 229
77 226 226
79 312 312
81 308 308
82 177 177
83 305 305
84 221 221
85 161 161
86 329 329
87 131 131
88 314 314
89 231 231
90 256 256
92 309 309
93 317 317
94 215 215
95 214 214
96 217 217
97 218 218
98 313 313
99 210 210
101 130 130
103 235 235
104 233 233
105 231 231
106 167 167
107 313 313
109 310 310
110 210 210
111 213 213
112 345 345
114 231 231
115 254 254
117 339 339
118 204 204
120 342 342
121 211 211
122 258 258
124 322 322
125 214 214
127 210 210
128 311 311
129 214 214
130 217 217
131 238 238
132 327 327
135 319 319
136 138 138
137 253 253
138 213 213
140 237 237
142 207 207
143 302 302
144 166 166
145 306 306
146 340 340
147 315 315
148 310 310
149 217 217

In [270]:
b

     LEAS_STATION  RTN_STATION       대여_X        대여_Y       반납_X        반납_Y
0             310          342  37.669687  126.761237  37.677995  126.766402
1             321          211  37.681812  126.769340  37.659728  126.772704
2             217          215  37.654141  126.783673  37.652254  126.778848
3             114            0  37.636688  126.831526   0.000000    0.000000
4             309          342  37.671278  126.761898  37.677995  126.766402
..            ...          ...        ...         ...        ...         ...
145           339          306  37.671468  126.735204  37.675838  126.747974
146           328          340  37.693468  126.773297  37.682513  126.769861
147           315          315  37.682443  126.756369  37.682443  126.756369
148           309          310  37.671278  126.761898  37.669687  126.761237
149           219          217  37.648388  126.787636  37.654141  126.783673

[150 rows x 6 columns]

In [271]:
b_leas = b[['LEAS_STATION','대여_X','대여_Y']]   #대여만
b_rtn = b[['RTN_STATION','반납_X','반납_Y']]     # 반납만 , print해보면 알 수 있음.

In [272]:
pip install folium

Requirement already satisfied: folium in c:\anaconda3\lib\site-packages (0.11.0)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from folium) (1.18.5)
Requirement already satisfied: jinja2>=2.9 in c:\anaconda3\lib\site-packages (from folium) (2.11.2)
Requirement already satisfied: requests in c:\anaconda3\lib\site-packages (from folium) (2.24.0)
Requirement already satisfied: branca>=0.3.0 in c:\anaconda3\lib\site-packages (from folium) (0.4.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests->folium) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests->folium) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\anaconda3\lib\site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\anaconda3\lib\site-packages (from requests->folium) (2.10)
Note: you may need to restart the kernel to use updated packages.

In [276]:
# https://mkjjo.github.io/python/2019/08/18/korea_population.html 사이트 5번에서 가져왔습니다.
import folium
from folium import plugins
from folium.plugins import HeatMap


m = folium.Map(location = [37.655647, 126.789453], zoom_start = 12)

heat_df = b_leas[['대여_X', '대여_Y']]

# List comprehension to make out list of lists
heat_data = [[row['대여_X'],row['대여_Y']] for index, row in heat_df.iterrows()]

# Plot it on the map
HeatMap(heat_data).add_to(m)

# Display the map
m

In [277]:
from folium import plugins
from folium.plugins import HeatMap


m = folium.Map(location = [37.655647, 126.789453], zoom_start = 12)

heat_df = b_rtn[['반납_X', '반납_Y']]

# List comprehension to make out list of lists
heat_data = [[row['반납_X'],row['반납_Y']] for index, row in heat_df.iterrows()]

# Plot it on the map
HeatMap(heat_data).add_to(m)

# Display the map
m

In [278]:
# https://mkjjo.github.io/python/2019/08/18/korea_population.html 사이트 5번에서 가져왔습니다.
from folium import plugins
from folium.plugins import HeatMap


m = folium.Map(location = [37.655647, 126.789453], zoom_start = 12)

heat_df = station_info[['위도', '경도']]

# List comprehension to make out list of lists
heat_data = [[row['위도'],row['경도']] for index, row in heat_df.iterrows()]

# Plot it on the map
HeatMap(heat_data).add_to(m)

# Display the map
m

In [261]:

station_info

     Station_ID          STATION_NAME  거치대 수량         위도          경도
0           101          어울림마을 701동 앞      20  37.654775  126.834584
1           103          대림e-편한세상106동      20  37.660442  126.840377
2           104               탄현마을8단지      25  37.698523  126.766042
3           105             KT 덕양지사 앞      20  37.655244  126.839261
4           106           원당역 앞 공영주차장      30  37.653410  126.842530
..          ...                   ...     ...        ...         ...
159         350  ★하이파크5단지 502동앞 버스정류장      20  37.697867  126.753089
160         351          ◆일산에듀포레 푸르지오      40  37.702259  126.767231
161         352            ◆꿈에그린203동앞      40  37.666425  126.749244
162         353            ◆꿈에그린106동앞      40  37.666720  126.750784
163         992                ★피프틴센터       4  37.637529  126.833760

[164 rows x 5 columns]